name       : libboost
version    : 1.72.0
release    : 27
source     :
    - https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz/download : c66e88d5786f2ca4dbebb14e06b566fb642a1a6947ad8cc9091f9f445134143f
homepage   : https://www.boost.org/
license    : BSL-1.0
component  : programming.library
summary    : Useful C++ source libraries
description: |
    Boost provides a set of free peer-reviewed portable C++ source libraries. It includes libraries for linear algebra, pseudorandom number generation, multithreading, image processing, regular expressions and unit testing.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - bzip2-devel
    - numpy
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-python3-include-dir-in-bootstrap.patch
    %patch -p1 < $pkgfiles/0002-revert-asymetric-coroutine.patch
build      : |
    ./bootstrap.sh --prefix=$installdir/usr \
        --libdir=$installdir/%libdir% \
        --with-python=/usr/bin/python3
install    : |
    ./b2 install \
        variant=release \
        threading=multi \
        link=shared,static \
        runtime-link=shared \
        -j %YJOBS%
