name       : libboost
version    : 1.62.0
release    : 11
source     :
    - https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz : 440a59f8bc4023dbe6285c9998b0f7fa288468b889746b1ef00e8b36c559dce1
homepage   : http://www.boost.org/
license    :
    - BSL-1.0
summary    : Useful C++ source libraries
builddeps  :
    - pkgconfig(icu-i18n)
component  : programming
description: |
    Boost provides a set of free peer-reviewed portable C++ source libraries. It includes libraries for linear algebra, pseudorandom number generation, multithreading, image processing, regular expressions and unit testing.
setup      : |
    ./bootstrap.sh --prefix=$installdir/usr --libdir=$installdir/%libdir%
build      : |
    ./b2 stage threading=multi link=shared,static runtime-link=shared -j $(echo %JOBS% | sed -e 's/-j//')
install    : |
    ./b2 install threading=multi link=shared,static runtime-link=shared -j $(echo %JOBS% | sed -e 's/-j//')
