name       : libboost
version    : 1.79.0
release    : 35
source     :
    - https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.7z : 6c97cf4f4a0eb00ed776c88065ab3f59e183fa5e65f6464ff94f92328352d9d6
homepage   : https://www.boost.org/
license    : BSL-1.0
component  : programming.library
summary    : Useful C++ source libraries
description: |
    Boost provides a set of free peer-reviewed portable C++ source libraries. It includes libraries for linear algebra, pseudorandom number generation, multithreading, image processing, regular expressions and unit testing.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - bzip2-devel
    - numpy
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-python3-include-dir-in-bootstrap.patch
    %patch -p1 < $pkgfiles/0001-json-array-erase-relocate.patch

    %patch -Np1 -d libs/locale < $pkgfiles/icu-locale-empty-vector.patch
    %patch -Np2 < $pkgfiles/ublas-c++20-iterator.patch
build      : |
    ./bootstrap.sh --prefix=$installdir/usr \
        --libdir=$installdir/%libdir% \
        --with-python=/usr/bin/python3
install    : |
    ./b2 install \
        variant=release \
        threading=multi \
        link=shared,static \
        runtime-link=shared \
        -j %YJOBS%
