name       : libboost
version    : 1.65.1
release    : 14
source     :
    - https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2 : 9807a5d16566c57fd74fb522764e0b134a8bbe6b6e8967b83afefd30dcd3be81
homepage   : https://www.boost.org/
license    : BSL-1.0
component  : programming.library
summary    : Useful C++ source libraries
description: |
    Boost provides a set of free peer-reviewed portable C++ source libraries. It includes libraries for linear algebra, pseudorandom number generation, multithreading, image processing, regular expressions and unit testing.
builddeps  :
    - pkgconfig(icu-i18n)
    - bzip2-devel
setup      : |
    ./bootstrap.sh --prefix=$installdir/usr --libdir=$installdir/%libdir%
build      : |
    ./b2 stage threading=multi link=shared,static runtime-link=shared -j %YJOBS%
install    : |
    ./b2 install threading=multi link=shared,static runtime-link=shared -j %YJOBS%
