name       : libboost
version    : 1.66.0
release    : 16
source     :
    - https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2 : 5721818253e6a0989583192f96782c4a98eb6204965316df9f5ad75819225ca9
homepage   : https://www.boost.org/
license    : BSL-1.0
component  : programming.library
summary    : Useful C++ source libraries
description: |
    Boost provides a set of free peer-reviewed portable C++ source libraries. It includes libraries for linear algebra, pseudorandom number generation, multithreading, image processing, regular expressions and unit testing.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(python3)
    - bzip2-devel
    - numpy
build        : |
    # This installs everything but python 3
    ./bootstrap.sh --prefix=$installdir/usr \
        --libdir=$installdir/%libdir% \
        --with-python=/usr/bin/python

    ./b2 install \
        variant=release \
        threading=multi \
        link=shared,static \
        runtime-link=shared \
        -j %YJOBS% \
        --build-dir=py2build
install    : |
    # This installs only python 3
    ./b2 --clean

    %patch -p1 < $pkgfiles/0001-Fix-python3-include-dir-in-bootstrap.patch

    ./bootstrap.sh --prefix=$installdir/usr \
        --libdir=$installdir/%libdir% \
        --with-python=/usr/bin/python3

    ./b2 install \
        variant=release \
        threading=multi \
        link=shared,static \
        runtime-link=shared \
        python=3.6 \
        -j %YJOBS% \
        --build-dir=py3build \
        --with-python
